

name: Build and deploy JAR app to Azure Web App - simple-spring-app

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install
      
    - uses: azure/login@v1.6.0
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'simplespringapp2'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7f47878fe7064bbfa1cc1b246d5163c7 }}
        package: '${{ github.workspace }}/target/*.jar'
